spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/cme
    username: postgres
    password: 666666

logging:
  level:
    com.baiyanbing.cme: error